//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinYourDesktop.Culture {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_Pirate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_Pirate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinYourDesktop.Culture.en-Pirate", typeof(en_Pirate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New ship.
        /// </summary>
        internal static string btnCreate {
            get {
                return ResourceManager.GetString("btnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make me new ship!.
        /// </summary>
        internal static string btnCreate_MouseEnter {
            get {
                return ResourceManager.GetString("btnCreate_MouseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check ship.
        /// </summary>
        internal static string btnDebug {
            get {
                return ResourceManager.GetString("btnDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check me ship!.
        /// </summary>
        internal static string btnDebug_MouseEnter {
            get {
                return ResourceManager.GetString("btnDebug_MouseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify ship.
        /// </summary>
        internal static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod me ship!.
        /// </summary>
        internal static string btnEdit_MouseEnter {
            get {
                return ResourceManager.GetString("btnEdit_MouseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPEN.
        /// </summary>
        internal static string btnOpen {
            get {
                return ResourceManager.GetString("btnOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arr, open file!.
        /// </summary>
        internal static string btnOpen_MouseEnter {
            get {
                return ResourceManager.GetString("btnOpen_MouseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sail ship.
        /// </summary>
        internal static string btnRun {
            get {
                return ResourceManager.GetString("btnRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventure time, boys!.
        /// </summary>
        internal static string btnRun_MouseEnter {
            get {
                return ResourceManager.GetString("btnRun_MouseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESTROY.
        /// </summary>
        internal static string btnRunClear {
            get {
                return ResourceManager.GetString("btnRunClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove traces boys!!!.
        /// </summary>
        internal static string btnRunClear_MouseEnter {
            get {
                return ResourceManager.GetString("btnRunClear_MouseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHOOT.
        /// </summary>
        internal static string btnRunWithDebugger {
            get {
                return ResourceManager.GetString("btnRunWithDebugger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIRE AWAY BOYS!!.
        /// </summary>
        internal static string btnRunWithDebugger_MouseEnter {
            get {
                return ResourceManager.GetString("btnRunWithDebugger_MouseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me ABC&apos;s!.
        /// </summary>
        internal static string lblSettingsLanguage {
            get {
                return ResourceManager.GetString("lblSettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thing.
        /// </summary>
        internal static string tsmApplication {
            get {
                return ResourceManager.GetString("tsmApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About me thing.
        /// </summary>
        internal static string tsmiAbout {
            get {
                return ResourceManager.GetString("tsmiAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELP MAKE SHIP.
        /// </summary>
        internal static string tsmiCreationWizard {
            get {
                return ResourceManager.GetString("tsmiCreationWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helpin&apos; me make new ship!.
        /// </summary>
        internal static string tsmiCreationWizard_MouseEnter {
            get {
                return ResourceManager.GetString("tsmiCreationWizard_MouseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        internal static string tsmiDebugger {
            get {
                return ResourceManager.GetString("tsmiDebugger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOD.
        /// </summary>
        internal static string tsmiEditor {
            get {
                return ResourceManager.GetString("tsmiEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELP ME FAM (English).
        /// </summary>
        internal static string tsmiHelp {
            get {
                return ResourceManager.GetString("tsmiHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me home.
        /// </summary>
        internal static string tsmiHome {
            get {
                return ResourceManager.GetString("tsmiHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroy me thing.
        /// </summary>
        internal static string tsmiQuit {
            get {
                return ResourceManager.GetString("tsmiQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild me thing!.
        /// </summary>
        internal static string tsmiRestart {
            get {
                return ResourceManager.GetString("tsmiRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change me look.
        /// </summary>
        internal static string tsmiSettings {
            get {
                return ResourceManager.GetString("tsmiSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me tools!.
        /// </summary>
        internal static string tsmTools {
            get {
                return ResourceManager.GetString("tsmTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ships!.
        /// </summary>
        internal static string tsmView {
            get {
                return ResourceManager.GetString("tsmView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrr, ay mate!.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
