//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinYourDesktop.Culture {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_Pirate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_Pirate() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinYourDesktop.Culture.en-Pirate", typeof(en_Pirate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New ship.
        /// </summary>
        internal static string btnCreate {
            get {
                return ResourceManager.GetString("btnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Make me new ship!.
        /// </summary>
        internal static string btnCreate_MouseEnter {
            get {
                return ResourceManager.GetString("btnCreate_MouseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check ship.
        /// </summary>
        internal static string btnDebug {
            get {
                return ResourceManager.GetString("btnDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check me ship!.
        /// </summary>
        internal static string btnDebug_MouseEnter {
            get {
                return ResourceManager.GetString("btnDebug_MouseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modify ship.
        /// </summary>
        internal static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mod me ship!.
        /// </summary>
        internal static string btnEdit_MouseEnter {
            get {
                return ResourceManager.GetString("btnEdit_MouseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OPEN.
        /// </summary>
        internal static string btnOpen {
            get {
                return ResourceManager.GetString("btnOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arr, open file!.
        /// </summary>
        internal static string btnOpen_MouseEnter {
            get {
                return ResourceManager.GetString("btnOpen_MouseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sail ship.
        /// </summary>
        internal static string btnRun {
            get {
                return ResourceManager.GetString("btnRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adventure time, boys!.
        /// </summary>
        internal static string btnRun_MouseEnter {
            get {
                return ResourceManager.GetString("btnRun_MouseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DESTROY.
        /// </summary>
        internal static string btnRunClear {
            get {
                return ResourceManager.GetString("btnRunClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à remove traces boys!!!.
        /// </summary>
        internal static string btnRunClear_MouseEnter {
            get {
                return ResourceManager.GetString("btnRunClear_MouseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SHOOT.
        /// </summary>
        internal static string btnRunWithDebugger {
            get {
                return ResourceManager.GetString("btnRunWithDebugger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FIRE AWAY BOYS!!.
        /// </summary>
        internal static string btnRunWithDebugger_MouseEnter {
            get {
                return ResourceManager.GetString("btnRunWithDebugger_MouseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Me ABC&apos;s!.
        /// </summary>
        internal static string lblSettingsLanguage {
            get {
                return ResourceManager.GetString("lblSettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thing.
        /// </summary>
        internal static string tsmApplication {
            get {
                return ResourceManager.GetString("tsmApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About me thing.
        /// </summary>
        internal static string tsmiAbout {
            get {
                return ResourceManager.GetString("tsmiAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check.
        /// </summary>
        internal static string tsmiDebugger {
            get {
                return ResourceManager.GetString("tsmiDebugger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MOD.
        /// </summary>
        internal static string tsmiEditor {
            get {
                return ResourceManager.GetString("tsmiEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HELP ME FAM (English).
        /// </summary>
        internal static string tsmiHelp {
            get {
                return ResourceManager.GetString("tsmiHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Me home.
        /// </summary>
        internal static string tsmiHome {
            get {
                return ResourceManager.GetString("tsmiHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destroy me thing.
        /// </summary>
        internal static string tsmiQuit {
            get {
                return ResourceManager.GetString("tsmiQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rebuild me thing!.
        /// </summary>
        internal static string tsmiRestart {
            get {
                return ResourceManager.GetString("tsmiRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change me look.
        /// </summary>
        internal static string tsmiSettings {
            get {
                return ResourceManager.GetString("tsmiSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Me tools!.
        /// </summary>
        internal static string tsmTools {
            get {
                return ResourceManager.GetString("tsmTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ships!.
        /// </summary>
        internal static string tsmView {
            get {
                return ResourceManager.GetString("tsmView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arrr, ay mate!.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
