//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinYourDesktop.Culture {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinYourDesktop.Culture.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string btnCreate {
            get {
                return ResourceManager.GetString("btnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an entry.
        /// </summary>
        internal static string btnCreate_MouseEnter {
            get {
                return ResourceManager.GetString("btnCreate_MouseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string btnDebug {
            get {
                return ResourceManager.GetString("btnDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug an entry.
        /// </summary>
        internal static string btnDebug_MouseEnter {
            get {
                return ResourceManager.GetString("btnDebug_MouseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit an entry.
        /// </summary>
        internal static string btnEdit_MouseEnter {
            get {
                return ResourceManager.GetString("btnEdit_MouseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string btnOpen {
            get {
                return ResourceManager.GetString("btnOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the file to run.
        /// </summary>
        internal static string btnOpen_MouseEnter {
            get {
                return ResourceManager.GetString("btnOpen_MouseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string btnRun {
            get {
                return ResourceManager.GetString("btnRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run an entry.
        /// </summary>
        internal static string btnRun_MouseEnter {
            get {
                return ResourceManager.GetString("btnRun_MouseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string btnRunCopy {
            get {
                return ResourceManager.GetString("btnRunCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the output to the clipboard.
        /// </summary>
        internal static string btnRunCopy_MouseEnter {
            get {
                return ResourceManager.GetString("btnRunCopy_MouseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string btnRunWithDebugger {
            get {
                return ResourceManager.GetString("btnRunWithDebugger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run the current file.
        /// </summary>
        internal static string btnRunWithDebugger_MouseEnter {
            get {
                return ResourceManager.GetString("btnRunWithDebugger_MouseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnSettingsSave {
            get {
                return ResourceManager.GetString("btnSettingsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (en-US).
        /// </summary>
        internal static string cboSettingsLanguage {
            get {
                return ResourceManager.GetString("cboSettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string lblSettingsLanguage {
            get {
                return ResourceManager.GetString("lblSettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App.
        /// </summary>
        internal static string tsmApplication {
            get {
                return ResourceManager.GetString("tsmApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string tsmiAbout {
            get {
                return ResourceManager.GetString("tsmiAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Wizard.
        /// </summary>
        internal static string tsmiCreationWizard {
            get {
                return ResourceManager.GetString("tsmiCreationWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the file creation wizard for DESKTOP files.
        /// </summary>
        internal static string tsmiCreationWizard_MouseEnter {
            get {
                return ResourceManager.GetString("tsmiCreationWizard_MouseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugger.
        /// </summary>
        internal static string tsmiDebugger {
            get {
                return ResourceManager.GetString("tsmiDebugger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        internal static string tsmiEditor {
            get {
                return ResourceManager.GetString("tsmiEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string tsmiHelp {
            get {
                return ResourceManager.GetString("tsmiHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string tsmiHome {
            get {
                return ResourceManager.GetString("tsmiHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string tsmiQuit {
            get {
                return ResourceManager.GetString("tsmiQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string tsmiRestart {
            get {
                return ResourceManager.GetString("tsmiRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string tsmiSettings {
            get {
                return ResourceManager.GetString("tsmiSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string tsmTools {
            get {
                return ResourceManager.GetString("tsmTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string tsmView {
            get {
                return ResourceManager.GetString("tsmView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello!.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
