//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinYourDesktop.Culture {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class fr_FR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal fr_FR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinYourDesktop.Culture.fr-FR", typeof(fr_FR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer.
        /// </summary>
        internal static string btnCreate {
            get {
                return ResourceManager.GetString("btnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer un nouveau fichier.
        /// </summary>
        internal static string btnCreate_MouseEnter {
            get {
                return ResourceManager.GetString("btnCreate_MouseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Débuggeur.
        /// </summary>
        internal static string btnDebug {
            get {
                return ResourceManager.GetString("btnDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Débugger un fichier.
        /// </summary>
        internal static string btnDebug_MouseEnter {
            get {
                return ResourceManager.GetString("btnDebug_MouseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Éxecute le fichier.
        /// </summary>
        internal static string btnDebuggerRun_MouseEnter {
            get {
                return ResourceManager.GetString("btnDebuggerRun_MouseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Éxecuter.
        /// </summary>
        internal static string btnRun {
            get {
                return ResourceManager.GetString("btnRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Éxecuter un fichier.
        /// </summary>
        internal static string btnRun_MouseEnter {
            get {
                return ResourceManager.GetString("btnRun_MouseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder.
        /// </summary>
        internal static string btnSettingsSave {
            get {
                return ResourceManager.GetString("btnSettingsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français (French).
        /// </summary>
        internal static string cboSettingsLanguage {
            get {
                return ResourceManager.GetString("cboSettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détecter la langue automatiquement.
        /// </summary>
        internal static string chkSettingsAutoDetectLanguage {
            get {
                return ResourceManager.GetString("chkSettingsAutoDetectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thème sombre.
        /// </summary>
        internal static string chkSettingsDarkTheme {
            get {
                return ResourceManager.GetString("chkSettingsDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activer les styles visuels*.
        /// </summary>
        internal static string chkSettingsEnableVisualStyles {
            get {
                return ResourceManager.GetString("chkSettingsEnableVisualStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est-vous sûre d&apos;associer les fichiers desktop avec l&apos;application au répertoire courrant?.
        /// </summary>
        internal static string DialogAssignFile {
            get {
                return ResourceManager.GetString("DialogAssignFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association enregistrée!.
        /// </summary>
        internal static string DialogAssignFileSuccess {
            get {
                return ResourceManager.GetString("DialogAssignFileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigner les fichiers desktop.
        /// </summary>
        internal static string DialogAssignFileTitle {
            get {
                return ResourceManager.GetString("DialogAssignFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue.
        /// </summary>
        internal static string lblSettingsLanguage {
            get {
                return ResourceManager.GetString("lblSettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Besoin de redémarrer l&apos;application.
        /// </summary>
        internal static string lblSettingsRequireRestart {
            get {
                return ResourceManager.GetString("lblSettingsRequireRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceci n&apos;est pas un fichier desktop!.
        /// </summary>
        internal static string Misc_ErrNotDesktopFile {
            get {
                return ResourceManager.GetString("Misc_ErrNotDesktopFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun fichier d&apos;ouvert.
        /// </summary>
        internal static string MiscNoFile {
            get {
                return ResourceManager.GetString("MiscNoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonjour!.
        /// </summary>
        internal static string MiscWelcome {
            get {
                return ResourceManager.GetString("MiscWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App.
        /// </summary>
        internal static string tsmApplication {
            get {
                return ResourceManager.GetString("tsmApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Débuggeur.
        /// </summary>
        internal static string tsmDebugger {
            get {
                return ResourceManager.GetString("tsmDebugger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier.
        /// </summary>
        internal static string tsmDebuggerFile {
            get {
                return ResourceManager.GetString("tsmDebuggerFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À propos.
        /// </summary>
        internal static string tsmiAbout {
            get {
                return ResourceManager.GetString("tsmiAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À propos de WinYourDesktop!.
        /// </summary>
        internal static string tsmiAbout_MouseEnter {
            get {
                return ResourceManager.GetString("tsmiAbout_MouseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associer avec les fichiers desktop.
        /// </summary>
        internal static string tsmiAssignDesktopFiles {
            get {
                return ResourceManager.GetString("tsmiAssignDesktopFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant de création.
        /// </summary>
        internal static string tsmiCreationWizard {
            get {
                return ResourceManager.GetString("tsmiCreationWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiche l&apos;assistant de création de fichier desktop.
        /// </summary>
        internal static string tsmiCreationWizard_MouseEnter {
            get {
                return ResourceManager.GetString("tsmiCreationWizard_MouseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Débuggeur.
        /// </summary>
        internal static string tsmiDebugger {
            get {
                return ResourceManager.GetString("tsmiDebugger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effacer.
        /// </summary>
        internal static string tsmiDebuggerClear {
            get {
                return ResourceManager.GetString("tsmiDebuggerClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effacer la sortie.
        /// </summary>
        internal static string tsmiDebuggerClear_MouseEnter {
            get {
                return ResourceManager.GetString("tsmiDebuggerClear_MouseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copier au presse-papier.
        /// </summary>
        internal static string tsmiDebuggerCopyToClipboard {
            get {
                return ResourceManager.GetString("tsmiDebuggerCopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copier la sortie au presse-papier.
        /// </summary>
        internal static string tsmiDebuggerCopyToClipboard_MouseEnter {
            get {
                return ResourceManager.GetString("tsmiDebuggerCopyToClipboard_MouseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir.
        /// </summary>
        internal static string tsmiDebuggerOpen {
            get {
                return ResourceManager.GetString("tsmiDebuggerOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir un fichier.
        /// </summary>
        internal static string tsmiDebuggerOpen_MouseEnter {
            get {
                return ResourceManager.GetString("tsmiDebuggerOpen_MouseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Éxecuter.
        /// </summary>
        internal static string tsmiDebuggerRun {
            get {
                return ResourceManager.GetString("tsmiDebuggerRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Éxecute le fichier.
        /// </summary>
        internal static string tsmiDebuggerRun_MouseEnter {
            get {
                return ResourceManager.GetString("tsmiDebuggerRun_MouseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aide.
        /// </summary>
        internal static string tsmiHelp {
            get {
                return ResourceManager.GetString("tsmiHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceuil.
        /// </summary>
        internal static string tsmiHome {
            get {
                return ResourceManager.GetString("tsmiHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitter.
        /// </summary>
        internal static string tsmiQuit {
            get {
                return ResourceManager.GetString("tsmiQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redémarrer.
        /// </summary>
        internal static string tsmiRestart {
            get {
                return ResourceManager.GetString("tsmiRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres.
        /// </summary>
        internal static string tsmiSettings {
            get {
                return ResourceManager.GetString("tsmiSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outils.
        /// </summary>
        internal static string tsmTools {
            get {
                return ResourceManager.GetString("tsmTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string tsmView {
            get {
                return ResourceManager.GetString("tsmView", resourceCulture);
            }
        }
    }
}
